### ISSUE TITLE
Game Logic/Playercount

### ISSUE THREAD

**Issue by elsantner** [elsantner/Risk#2]
Soll man ausschließlich mit 2 Spielern oder mit 3+ Spielern spielen können?
- Risiko hat eigene Regeln für 2 Spieler. --> 3+ Regeln müssten nicht implementiert werden

**Comment by cusAAU** [comment]
ich würde mich für eine Variante entscheiden und diese implementieren. 3+ Spielern klingt für mich nach mehr Spaß

**Comment by elsantner** [comment]
Einigung: Offizielle 3+ Spieler Regeln für 2-6 Spieler.
