### ISSUE TITLE
Game Logic/Schummelfunktion

### ISSUE THREAD

**Issue by elsantner** [elsantner/Risk#3]
- Schüttelt man das Smartphone während der Würfel-Animation, so erhöht sich die Wahrscheinlichkeit für gute Zahlen (zB Doppel-6) erheblich.
	- Gegner hat/haben die Möglichkeit, das Würfel-Ergebnis des Spielers, der gerade am Zug ist, "anzuzweifeln" (ihn des Schummeln zu beschuldigen)
	- Hat der Spieler tatsächlich geschummelt, so entsteht ein Nachteil für ihn. 
	  Hat der Spieler nicht geschummelt, so entsteht ein Nachteil für den "Ankläger". 
	- Mögliche Nachteile (ist zu entscheiden): 
		- Der fälschlich beschuldigte Spieler / der rechtmäßige "Ankläger" erhält Bonus-Einheiten.
		- Eine Runde aussetzten (wahrscheinlich zu extremer Vor- bzw. Nachteil)

**Comment by cusAAU** [comment]
ja, mit Bonus Einheiten klingt es gut, was dann am Ende des Spieles in die Auswertung einkalkuliert wird

**Comment by WilhelmStu** [comment]
Alternative Schummelfunktion:
- Man kann eine "Fake" Joker Karte nutzen und damit leichter ein Set vervolständigen. 
- Immer wenn jemand einen Joker spielt können andere Spieler es anzweifeln.
- Wenn der beschuldigte Spieler, wirklich einen Falschen Joker gespielt hat verliert er seine beiden anderen Karten und bekommt keine Einheiten.
- Hat der Ankläger allerdings unrecht (also es wurde ein echter Joker gespielt) so muss er eine oder mehrere Karten dem Beschuldigten geben.

**Comment by elsantner** [comment]
> Alternative Schummelfunktion:
> 
> * Man kann eine "Fake" Joker Karte nutzen und damit leichter ein Set vervolständigen.
> * Immer wenn jemand einen Joker spielt können andere Spieler es anzweifeln.
> * Wenn der beschuldigte Spieler, wirklich einen Falschen Joker gespielt hat verliert er seine beiden anderen Karten und bekommt keine Einheiten.
> * Hat der Ankläger allerdings unrecht (also es wurde ein echter Joker gespielt) so muss er eine oder mehrere Karten dem Beschuldigten geben.

Das ist auch eine gute Idee! 
Allerdings müssten wir uns dann eine andere Möglichkeit ausdenken, einen Smartphone Sensor zu verwenden. (Bei der oben beschriebenen Variante wird das Schütteln ja durch diesen erkannt.)

**Comment by elsantner** [comment]
Entscheidung: 
> * Schüttelt man das Smartphone während der Würfel-Animation, so erhöht sich die Wahrscheinlichkeit für gute Zahlen (zB Doppel-6) erheblich.
>   
>   * Gegner hat/haben die Möglichkeit, das Würfel-Ergebnis des Spielers, der gerade am Zug ist, "anzuzweifeln" (ihn des Schummeln zu beschuldigen)
>   * Hat der Spieler tatsächlich geschummelt, so entsteht ein Nachteil für ihn.
>     Hat der Spieler nicht geschummelt, so entsteht ein Nachteil für den "Ankläger".
>   * Mögliche Nachteile (ist zu entscheiden):
>     
>     * Der fälschlich beschuldigte Spieler / der rechtmäßige "Ankläger" erhält Bonus-Einheiten.
>     * Eine Runde aussetzten (wahrscheinlich zu extremer Vor- bzw. Nachteil)
