### ISSUE TITLE
Technical/LibGDX

### ISSUE THREAD

**Issue by elsantner** [elsantner/Risk#5]
Sollen wir LibGDX verwenden?
	- Einarbeitungsaufwand, dafür wahrscheinlich flüssiger und optisch ansprechender umsetzbar.
	- Testbarkeit im Vergliech zu Standard Android?

**Comment by cusAAU** [comment]
Muss nicht, kann aber gerne verwendet werden (laut Tutor)

**Comment by elsantner** [comment]
Endscheidung: LibGDX wird verwendet
