### ISSUE TITLE
Write Management Summary

### ISSUE THREAD

**Issue by cusAAU** [elsantner/Risk#7]
First draft. Bitte das Dokument weiter bearbeiten, ergänzen und formatieren. Nicht mehr als eine Seite schreiben!

[Management-Summary_Risk_V001.docx](https://github.com/elsantner/Risk/files/4402261/Management-Summary_Risk_V001.docx)

**Comment by carinadeutschl** [comment]
[Management_Summary.docx](https://github.com/elsantner/Risk/files/4403306/Management_Summary.docx)

**Comment by elsantner** [comment]
Ich habe die wichtigsten besprochenen Ideen und Erkenntnisse aus den Issues 1-6 hinzugefügt.
Allerdings musste ich gewisse Passagen etwas kürzen (hauptsächlich Spielbeschreibung), da es sich sonst platz-technisch nicht ausgegangen wäre.

[Risk_Management_Summary_V002.docx](https://github.com/elsantner/Risk/files/4403858/Risk_Management_Summary_V002.docx)
